// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0uWaKWf0E8cLKzG0UTivowdJmO4ZK4pw',
    appId: '1:36244654330:web:9d65fea7a8441aed47e143',
    messagingSenderId: '36244654330',
    projectId: 'unimark-ffb10',
    authDomain: 'unimark-ffb10.firebaseapp.com',
    storageBucket: 'unimark-ffb10.firebasestorage.app',
    measurementId: 'G-LZF6LKQZLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0uWaKWf0E8cLKzG0UTivowdJmO4ZK4pw',
    appId: '1:36244654330:android:9d65fea7a8441aed47e143',
    messagingSenderId: '36244654330',
    projectId: 'unimark-ffb10',
    authDomain: 'unimark-ffb10.firebaseapp.com',
    storageBucket: 'unimark-ffb10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0uWaKWf0E8cLKzG0UTivowdJmO4ZK4pw',
    appId: '1:36244654330:ios:9d65fea7a8441aed47e143',
    messagingSenderId: '36244654330',
    projectId: 'unimark-ffb10',
    authDomain: 'unimark-ffb10.firebaseapp.com',
    storageBucket: 'unimark-ffb10.firebasestorage.app',
    iosBundleId: 'com.example.unimark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0uWaKWf0E8cLKzG0UTivowdJmO4ZK4pw',
    appId: '1:36244654330:macos:9d65fea7a8441aed47e143',
    messagingSenderId: '36244654330',
    projectId: 'unimark-ffb10',
    authDomain: 'unimark-ffb10.firebaseapp.com',
    storageBucket: 'unimark-ffb10.firebasestorage.app',
    iosBundleId: 'com.example.unimark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0uWaKWf0E8cLKzG0UTivowdJmO4ZK4pw',
    appId: '1:36244654330:web:9d65fea7a8441aed47e143',
    messagingSenderId: '36244654330',
    projectId: 'unimark-ffb10',
    authDomain: 'unimark-ffb10.firebaseapp.com',
    storageBucket: 'unimark-ffb10.firebasestorage.app',
    measurementId: 'G-LZF6LKQZLD',
  );
}